sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --no-cache -t izonder/dany-ci .

script:
  - docker run -it --rm izonder/dany-ci docker --version
  - docker run -it --rm izonder/dany-ci sh -c 'node --version'
  - docker run -it --rm izonder/dany-ci sh -c 'yarn --version'
  - docker run -it --rm izonder/dany-ci sh -c 'yarn global add npm'

after_success:
  - docker tag izonder/dany-ci izonder/dany-ci:12
  - docker push izonder/dany-ci:12
