sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build --no-cache -t izonder/dany-ci .

script:
  - docker run -it --rm izonder/dany-ci docker --version
  - docker run -it --rm izonder/dany-ci sh -c 'node --version'
  - docker run -it --rm izonder/dany-ci sh -c 'yarn --version'
  - docker run -it --rm izonder/dany-ci sh -c 'yarn global add npm'

after_success:
  - curl -X POST https://registry.hub.docker.com/u/izonder/dany-ci/trigger/$DOCKER_TRIGGER_TOKEN/
