name: Build Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker info
          docker build --no-cache --pull -t izonder/dany-ci .
      - name: Test the image
        run: |
          docker run --rm izonder/dany-ci docker --version
          docker run --rm izonder/dany-ci sh -c 'node --version'
          docker run --rm izonder/dany-ci sh -c 'yarn --version'
          docker run --rm izonder/dany-ci sh -c 'yarn global add npm'
      - name: Assign the tag
        run: docker tag izonder/dany-ci izonder/dany-ci:14
      - name: Publish the image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push izonder/dany-ci:14
